# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5707f6250c02ad09a0fdd9ae0f4fed46512a9d384387a4b62ba114fad9907c5dead39a1cc8c7824c9ed4b9d922e0cf0251612231d18e590db07d0582c324f96

test:
  secret_key_base: 9c6160d28909dbfdd2334ea0c3e3c27497ba780b6ad1204db2dec5226190d9cad6ba95440036f5325167a1cb6a02ec15bb3b93eeccc3a7bbe2ad06e964f05861

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
